package inheritance;

public class Multilevel_Inheritance_Study {

	public static void main(String[] args) {
		
		// FOR SUPERMOST CLASS
		System.out.println();
		System.out.println("CALLING USING SUPERMOST CLASS OBJECT ");
		
		Father f = new Father();  // CREATED OBJECT OF SUPERMOST CLASS
		
		f.home(); // CALLING OWN PROPERTY USING OWN OBJECT OF SUPERMOST CLASS
		f.love(); // CALLING OWN PROPERTY USING OWN OBJECT OF SUPERMOST CLASS
		
		// FOR SUB CLASS FOR FATHER AND SUPER CLASS FOR GRANDSON---SUPER CLASS
		System.out.println();
		System.out.println("CALLING USING SUPER CLASS OBJECT");
		
		Son s = new Son();  // CREATED OBJECT OF CHILD CLASS-- SUB-CLASS FOR FATHER----SUPERCLASS FOR GRANDSON
		
		s.bike();  //CALLING OWN PROPERTY USING OWN OBJECT OF SON CLASS
		
		s.home();  // CALLING SUPERMOST CLASS PROPERTY USING SUB-CLASS OBJECT OF SON CLASS
		s.love();  // CALLING SUPERMOST CLASS PROPERTY USING SUB-CLASS OBJECT OF SON CLASS
		
		// FOR SUB CLASS GRAND SON-- SUB-CLASS
		System.out.println();
		System.out.println("CALLING USING SUB-CLASS OBJECT");
		
		GrandSon gs = new GrandSon();  //CREATED OBJECT OF SUB-CLASS GRANDSON
		
		gs.cycle(); //CALLING OWN PROPERTY USING OWN OBJECT OF GRANDSON CLASS
		
		gs.bike(); // CALLING SUPERCLASS PROPERTY USING SUB-CLASS OBJECT
		
		gs.home();  // CALLING SUPERMOST CLASS PROPERTY USING SUB-CLASS OBJECT
		gs.love();  // CALLING SUPERMOST CLASS PROPERTY USING SUB-CLASS OBJECT

	}

}
