package inheritance;

public class Single_Level_Inheritance_Study {

	public static void main(String[] args) {
		
		// FOR SUPER CLASS
		
		System.out.println("CALLING FATHER CLASS PROPERTY USING FATHER CLASS OBJECT");
		
		Father f =new Father();   // CREATED OBJECT OF SUPERCLASS (FATHER)
		
		f.home();  //CALLING FATHER(SUPERCLASS) OWN PROPERTY USING OWN OBJECT OF FATHER CLASS 
		f.love();  //CALLING FATHER(SUPERCLASS) OWN PROPERTY USING OWN OBJECT OF FATHER CLASS 
		
		// f.bike();----WE CANNOT CALL CHILD CLASS (SUB CLASS) PROPERTY USING FATHER(SUPER CLASS) OBJECT
		
		System.out.println();
		// FOR SUB-CLASS IN WHICH FATHER EXTENDS IN
		System.out.println("CALLING SON AND FATHER CLASS PROPERTY USING ONLY SON CLASS OBJECT (INHERITANCE)");
		
		Son s = new Son();
		
		s.bike();    // CALLING SON CLASS'S OWN PROPERTY BIKE METHOD
		
		s.home();    // CALLING FATHER (BASE CLASS) PROPERTY USING CHILD CLASS OBJECT (INHERITANCE)
		s.love();    // CALLING FATHER (BASE CLASS) PROPERTY USING CHILD CLASS OBJECT (INHERITANCE)
		

	}

}
