package interfaceStudy;

public interface MyInterface {

	// 100% abstract/ incomplete
	
	int a=90;  //  variable in interface is by default static and final
	
	// a=a+10;---CANT MODIFY VALUE OF VARIABLE IN INTERFACE AS VARIBALES ARE FINAL--- NO MODIFICATION ALLOWED
	
	public void test();  // METHODS IN INTERFACE ARE BY DEFAULT PUBLIC AND ABSTRACT
	
	void test1();        // AS METHODS ARE BY DEFAULT PUBLIC AND ABSTRACT
	                     // NOT NECCESSARY TO WRITE PUBLIC AND ABSTRACT IN FRONT OF METHOD
	
	void test2();
	
	
	
	//public MyInterface()
	//{
	//     CONSTRUCTOR CONCERT IS NOT PRESENT INSIDE INTERFACE---AS WE CANT CREATE  OBJECT OF INTERFACE
	//	}
	
	//MyInterface mi = new MyInterface(); ---- OBJECT OF INTERFACE CANT BE CREATED AS METHOD ARE INCOMPLETE IN IT
	
	// CANT CREATE INSTANCE VARIABLE/NONSTATIC VARIABLE---OBJECT==INSTANCE VARIABLE/NONSTATIC VARIABLE
	// INSTANCE VARIABLE MEANS IT IS LIMITED TO THAT CLASS ONLY---CAN NOT USE OUTSIDE THE CLASS
}
